import type { CaptionPreset } from '../types';

export const CAPTION_PRESETS: CaptionPreset[] = [
    {
        id: 'hormozi',
        name: 'Hormozi',
        category: 'creator',
        preview: 'HOT',
        description: 'Big uppercase words with a gold active-word punch.',
        exportMode: 'ass',
        style: {
            displayMode: 'word-by-word',
            fontFamily: 'Montserrat',
            fontWeight: 900,
            fontSize: 56,
            color: '#ffffff',
            textTransform: 'uppercase',
            activeWordColor: '#FFD700',
            activeWordScale: 1.2,
            strokeEnabled: true,
            strokeColor: '#000000',
            strokeWidth: 4,
            showBackground: false,
            glowEnabled: true,
            glowColor: '#FFD700',
            animation: 'pop',
        },
    },
    {
        id: 'karaoke-fill',
        name: 'Karaoke Fill',
        category: 'creator',
        preview: 'SING',
        description: 'Smooth fill captions for podcasts, music, and monologues.',
        exportMode: 'ass',
        style: {
            displayMode: 'typewriter',
            fontFamily: 'Poppins',
            fontWeight: 800,
            fontSize: 50,
            color: '#ffffff',
            activeWordColor: '#00D4FF',
            strokeEnabled: true,
            strokeColor: '#000000',
            strokeWidth: 3,
            showBackground: false,
            glowEnabled: true,
            glowColor: '#00D4FF',
            animation: 'fade',
        },
    },
    {
        id: 'veed-clean',
        name: 'VEED Clean',
        category: 'clean',
        preview: 'BOX',
        description: 'Readable boxed active words for explainers and interviews.',
        exportMode: 'ass',
        style: {
            displayMode: 'line-by-line',
            fontFamily: 'Inter',
            fontWeight: 800,
            fontSize: 46,
            color: '#ffffff',
            activeWordColor: '#111111',
            activeWordBackground: true,
            activeWordBackgroundColor: '#FFD700',
            strokeEnabled: false,
            showBackground: true,
            backgroundColor: '#000000',
            backgroundOpacity: 0.7,
            backgroundRadius: 8,
            animation: 'fade',
        },
    },
    {
        id: 'podcast-bold',
        name: 'Podcast Bold',
        category: 'podcast',
        preview: 'TALK',
        description: 'High-contrast captions tuned for talking-head clips.',
        exportMode: 'ass',
        style: {
            displayMode: 'flow',
            fontFamily: 'Outfit',
            fontWeight: 800,
            fontSize: 48,
            color: '#ffffff',
            activeWordColor: '#00FF88',
            strokeEnabled: true,
            strokeColor: '#000000',
            strokeWidth: 3,
            shadowEnabled: true,
            animation: 'scale',
        },
    },
    {
        id: 'gamer',
        name: 'Gamer',
        category: 'gaming',
        preview: 'GG',
        description: 'Neon punch for streams, gaming clips, and reactions.',
        exportMode: 'ass',
        style: {
            displayMode: 'word-by-word',
            fontFamily: 'Outfit',
            fontWeight: 900,
            fontSize: 52,
            color: '#ffffff',
            activeWordColor: '#A78BFA',
            strokeEnabled: true,
            strokeColor: '#000000',
            strokeWidth: 3,
            glowEnabled: true,
            glowColor: '#A78BFA',
            glowIntensity: 28,
            animation: 'bounce',
        },
    },
    {
        id: 'minimal-pro',
        name: 'Minimal Pro',
        category: 'clean',
        preview: 'Aa',
        description: 'Quiet, premium captions for founders and educators.',
        exportMode: 'ass',
        style: {
            displayMode: 'line-by-line',
            fontFamily: 'Inter',
            fontWeight: 650,
            fontSize: 42,
            color: '#ffffff',
            activeWordColor: '#ffffff',
            strokeEnabled: false,
            showBackground: true,
            backgroundColor: '#000000',
            backgroundOpacity: 0.62,
            backgroundRadius: 6,
            animation: 'fade',
        },
    },
    {
        id: 'education',
        name: 'Education',
        category: 'education',
        preview: '101',
        description: 'Clear keywords and number emphasis for learning clips.',
        exportMode: 'ass',
        style: {
            displayMode: 'flow',
            fontFamily: 'Poppins',
            fontWeight: 700,
            fontSize: 44,
            color: '#ffffff',
            activeWordColor: '#22C55E',
            autoEmphasize: true,
            emphasisColor: '#FFD700',
            strokeEnabled: true,
            strokeColor: '#000000',
            strokeWidth: 2,
            animation: 'fade',
        },
    },
    {
        id: 'hindi-urdu',
        name: 'Hindi/Urdu Friendly',
        category: 'multilingual',
        preview: 'HI',
        description: 'Larger, calmer captions for multilingual speech.',
        exportMode: 'ass',
        style: {
            displayMode: 'line-by-line',
            fontFamily: 'Poppins',
            fontWeight: 700,
            fontSize: 50,
            color: '#ffffff',
            activeWordColor: '#FFD700',
            strokeEnabled: true,
            strokeColor: '#000000',
            strokeWidth: 3,
            showBackground: true,
            backgroundColor: '#000000',
            backgroundOpacity: 0.55,
            animation: 'fade',
        },
    },
    {
        id: 'meme',
        name: 'Meme',
        category: 'meme',
        preview: 'LOL',
        description: 'Classic punchy meme text for reactions and jokes.',
        exportMode: 'ass',
        style: {
            displayMode: 'word-by-word',
            fontFamily: 'Arial',
            fontWeight: 900,
            fontSize: 54,
            color: '#ffffff',
            textTransform: 'uppercase',
            activeWordColor: '#FF6B6B',
            strokeEnabled: true,
            strokeColor: '#000000',
            strokeWidth: 5,
            glowEnabled: false,
            animation: 'pop',
        },
    },
];

export const findCaptionPreset = (id: string) =>
    CAPTION_PRESETS.find((preset) => preset.id === id);

